---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: podpincher
  name: podpincher
spec:
  type: "LoadBalancer"
  ports:
    - 
      port: 80
      targetPort: 4567
  selector:
    app: podpincher