apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: podpincher
spec:
  replicas: 1
  template:
    metadata:
      labels:
        cagby.io/color: FF33FF
        app: podpincher
    spec:
      containers:
      - image: quay.io/samsung_cnct/podpincher:latest
        imagePullPolicy: Always
        name: podpincher
        env:
        - name: KUBERNETES_API_VER
          value: v1
        - name: KUBERNETES_API_URL
          value: http://127.0.0.1:8001/api/
        ports:
        - containerPort: 4567
          hostPort: 4567
          protocol: TCP
      # TODO: Need to create our own kubectl container from
      # https://github.com/kubernetes/kubernetes/tree/master/examples/kubectl-container
      - image: "lachlanevenson/k8s-kubectl"
        name: kubectl
        args: [ "proxy", "-p",  "8001" ]
---
apiVersion: v1
kind: Service
metadata:
  labels:
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: PodPincher
  name: podpincher
spec:
  ports:
  - name: podpincher
    nodePort: 30977
    port: 4567
    protocol: TCP
    targetPort: 4567
  selector:
    app: podpincher
  sessionAffinity: None
  type: NodePort

